### PR TITLE
Fixed panic during kubeconfig generate

### LINKED ISSUE #432: Panic when trying to generate a kubeconfig with a <pending> `LoadBalancer`
Trying to generate a kubeconfig of a virtual cluster exposed with a LoadBalancer in a `<pending>` status will panic.

Image

```
-> % k3kcli kubeconfig generate --name cobra
INFO[0000] waiting for cluster to be available..        
INFO[0000] certificate CN=system:admin,O=system:masters signed by CN=k3s-client-ca@1753195520: notBefore=2025-07-22 14:45:20 +0000 UTC notAfter=2026-07-23 15:05:39 +0000 UTC 
E0801 17:05:39.410607   27779 panic.go:115] "Observed a panic" panic="runtime error: index out of range [0] with length 0" panicGoValue="runtime.boundsError{x:0, y:0, signed:true, code:0x0}" stacktrace=<
        goroutine 1 [running]:
        k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1ddb7a0, 0x2c43c80}, {0x19e8720, 0xc00040a168})
                /home/enrico/.asdf/installs/golang/1.24.2/packages/pkg/mod/k8s.io/apimachinery@v0.31.4/pkg/util/runtime/runtime.go:107 +0xbc
        k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x1ddb7a0, 0x2c43c80}, {0x19e8720, 0xc00040a168}, {0x2c43c80, 0x0, 0x440a98?})
                /home/enrico/.asdf/installs/golang/1.24.2/packages/pkg/mod/k8s.io/apimachinery@v0.31.4/pkg/util/runtime/runtime.go:82 +0x5a
        k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000002380?})
                /home/enrico/.asdf/installs/golang/1.24.2/packages/pkg/mod/k8s.io/apimachinery@v0.31.4/pkg/util/runtime/runtime.go:59 +0x105
        panic({0x19e8720?, 0xc00040a168?})
                /home/enrico/.asdf/installs/golang/1.24.2/go/src/runtime/panic.go:792 +0x132
        github.com/rancher/k3k/pkg/controller/kubeconfig.getURLFromService({0x1ddb7a0, 0x2c43c80}, {0x1de5540, 0xc000420a20}, 0xc000004808, {0xc000369508, 0xc})
                /home/enrico/Development/enrichman/k3k/pkg/controller/kubeconfig/kubeconfig.go:116 +0x879
        github.com/rancher/k3k/pkg/controller/kubeconfig.(*KubeConfig).Generate(0xc0005515a0, {0x1ddb7a0, 0x2c43c80}, {0x1de5540, 0xc000420a20}, 0xc000004808, {0xc000369508, 0xc})
                /home/enrico/Development/enrichman/k3k/pkg/controller/kubeconfig/kubeconfig.go:63 +0x196
        github.com/rancher/k3k/cli/cmds.NewKubeconfigGenerateCmd.generate.func1.1()
                /home/enrico/Development/enrichman/k3k/cli/cmds/kubeconfig.go:153 +0x57
        k8s.io/client-go/util/retry.OnError.func1()
```

This is because the LoadBalancer status is empty, and we are trying to access it anyway: https://github.com/rancher/k3k/blob/f85702dc2354a2e9e5eebee59b7904eb5a578677/pkg/controller/kubeconfig/kubeconfig.go#L116

### PR DESCRIPTION
**Pull request by enrichman**
Fix #432 

When a Cluster is exposed with a LoadBalancer but the IP is not yet issued the Status of the Service is empty, because the ExternalIP is still in a `<pending>` state.

This PR adds a check, and logs a warning.

image

### CODE REVIEW

File: pkg/controller/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -111,18 +111,32 @@ func getURLFromService(ctx context.Context, client client.Client, cluster *v1bet
...
-		ip = k3kService.Status.LoadBalancer.Ingress[0].IP
-		port = k3kService.Spec.Ports[0].Port
+		if len(k3kService.Status.LoadBalancer.Ingress) == 0 {
+			logrus.Warn("No ingress found in LoadBalancer service.")
+		} else {
+			ip = k3kService.Status.LoadBalancer.Ingress[0].IP
+		}
+
+		if len(k3kService.Spec.Ports) == 0 {
+			logrus.Warn("No exposed port in LoadBalancer service.")
```
Comment (bigkevmcd) [inline pkg/controller/kubeconfig/kubeconfig.go]: Should this be a different message from the one above?

Comment (enrichman) [reply pkg/controller/kubeconfig/kubeconfig.go]: Do you mean that it could be the same message, like "No exposed ports in service."?

I'm not even sure you can have a Service without a Port actually.

Comment (bigkevmcd) [reply pkg/controller/kubeconfig/kubeconfig.go]: Oops...should've clarified this, you can't have a Service without a Port, spec.ports is a required value.

Comment (enrichman) [reply pkg/controller/kubeconfig/kubeconfig.go]: Ah, awesome. So should I drop the check altogether? I'm fine with this, it simplify the code, and it was not really the reason of the PR. :slightly_smiling_face:
