### PR TITLE
Fixed CreatePod and UpdatePod in Virtual Kubelet for Downward API

### LINKED ISSUE #495: Permission issue with ingress installation
**Environmental Info:**
Host Cluster Version: 
v1.33.5+k3s1

Node(s) CPU architecture, OS, and Version: 
openSUSE Linux, x86

Host Cluster Configuration:
3 servers

K3K Cluster Configuration:
Everything default, shared cluster

**Describe the bug:**
The logs for `ingress-nginx-admission-patch-97zvq` show:
```
W1007 16:42:21.407074       1 client_config.go:667] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"err":"secrets \"ingress-nginx-admission\" is forbidden: User \"system:serviceaccount:ingress-nginx:ingress-nginx-admission\" cannot get resource \"secrets\" in API group \"\" in the namespace \"k3k-myvcluster\"","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:232","time":"2025-10-07T16:42:21Z"}
```

**Steps To Reproduce:**
Ran: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.3/deploy/static/provider/cloud/deploy.yaml`

**Expected behavior:**
For the nginx ingress controller to install properly.

**Actual behavior:**
The admission patch pods enter a crashloop.

### PR DESCRIPTION
**Pull request by enrichman**
Fix #495.

Between `v0.3.4` and `v.0.3.5` we introduced a regression. In shared mode when a Pod is created on the Host cluster the `fieldRef.fieldPath` were not hardcoded anymore, keeping the reference. This means that, for example, with `metadata.namespace` the Pod gets a reference on the real namespace is running on:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
```

The `$POD_NAMESPACE` is evaluated as `k3k-mycluster` for example, instead of the `default` where the Pod was scheduled instead (in the virtual cluster).

To avoid this issue we need to hardcode the value that are not reflecting the virtual cluster values, such as the metadata.name and the metadata.namespace. All the other values of the [downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) should be ok.

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: POD_NAME
      value: nginx
    - name: POD_NAMESPACE
      value: default
```

Some tests were added (e2e and unit) and also a test that will install the ingress-nginx controller.

This PR also adds the support for the `configMapKeyRef` and `secretkeyref`, that should match the translated name in the host.

### CODE REVIEW

File: tests/cluster_pod_test.go [hunk 1]
```diff
@@ -15,162 +19,263 @@ import (
...
+		})
+	})
+
+	When("installing the nginx-ingress controller", func() {
+		BeforeAll(func() {
+			By("installing the nginx-ingress controller")
+
+			Expect(os.WriteFile("vk-kubeconfig.yaml", virtualCluster.Kubeconfig, 0o644)).To(Succeed())
+
+			ingressNginx := "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/baremetal/deploy.yaml"
```
Comment (galal-hussein) [inline tests/cluster_pod_test.go]: Do we need to pull the file from Github?, I think we can store a local copy of the yaml in our testdata to be consistent with other tests

Comment (enrichman) [reply tests/cluster_pod_test.go]: Hm, that's a good tip. I will store it locally. :v: 
It's also better to avoid any issues with the network.

**Review by galal-hussein — APPROVED** [review]
