### PR TITLE
Fix for pod eviction in host cluster

### LINKED ISSUE #454: Pods deleted on the Host cluster are not reflected on the virtual cluster
**Environmental Info:**
Host Cluster Version: 
```
NAME          STATUS   ROLES                              AGE   VERSION          INTERNAL-IP       OS-IMAGE                              KERNEL-VERSION            CONTAINER-RUNTIME
downstream2   Ready    control-plane,etcd,master,worker   21d   v1.32.6+rke2r1     <none>        SUSE Linux Enterprise Server 15 SP6   6.4.0-150600.21-default   containerd://2.0.5-k3s1
```

Host Cluster Configuration:
Single node server
CNI: Calico

K3K Cluster Configuration:
```
apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: myk3kcluster
  namespace: k3k-myk3kcluster
spec:
  mode: shared
  persistence:
    storageClassName: longhorn
    storageRequestSize: 5Gi
    type: dynamic
  servers: 1
```
**Describe the bug:**
If I delete the `coredns` pod on the host cluster, it stays in `running` state in the virtual cluster. If I try to get the pod logs inside the virtual cluster I got: 

```
kube-system           coredns-5688667fd4-9ktbb                1/1     Running       0          7d17h
~ # kubectl logs -n kube-system coredns-5688667fd4-9ktbb
Error from server (InternalError): Internal error occurred: error getting container logs?): pods "coredns-5688667fd4-9ktbb-kube-system-myk3kcluster-636f726-18ee6" not found
```

**Expected behavior:**
When deleting a Pod in the host cluster, it should notify the associated resource in the virtual cluster to reflect the correct state.

### PR DESCRIPTION
**Pull request by enrichman**
This PR fixes #454. It adds a PodController that will observe the host pods, and when a pod owned by a Cluster is deleted, then it will delete the corresponding pod on the virtual cluster.

### CODE REVIEW

File: pkg/controller/cluster/pod.go [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+	if err := r.Client.Get(ctx, req.NamespacedName, &pod); err != nil {
+		if !apierrors.IsNotFound(err) {
+			return reconcile.Result{}, err
+		}
+
+		return reconcile.Result{}, ctrlruntimeclient.IgnoreNotFound(err)
+	}
+
+	owner := metav1.GetControllerOf(&pod)
+	if owner == nil || owner.APIVersion != v1alpha1.SchemeGroupVersion.String() || owner.Kind != "Cluster" {
```
Comment (galal-hussein) [inline pkg/controller/cluster/pod.go]: Not really sure if we should have a `filterResources` predicates, that way we will be consistent with our controllers that we have

**Review by galal-hussein — APPROVED** [review]

**Review by galal-hussein — APPROVED** [review]
