### PR TITLE
Fix Service reconciliation error loop

### LINKED ISSUE #496: Error while trying to reconcile Cluster owned services
After the merge of #484 we are looping and erroring while trying to reconcile some Cluster owned services:

```
{"level":"info","timestamp":"2025-10-08T10:27:36.003Z","msg":"ensuring service status to virtual cluster","controller":"k3k-service-controller","controllerGroup":"","controllerKind":"Service","Service":{"name":"k3k-test-shared-service-headless","namespace":"k3k-test-shared"},"namespace":"k3k-test-shared","name":"k3k-test-shared-service-headless","reconcileID":"73f59d0e-ea69-4aa2-b725-91bf8a7df130"}
{"level":"error","timestamp":"2025-10-08T10:27:36.005Z","msg":"Reconciler error","controller":"k3k-service-controller","controllerGroup":"","controllerKind":"Service","Service":{"name":"k3k-test-shared-service-headless","namespace":"k3k-test-shared"},"namespace":"k3k-test-shared","name":"k3k-test-shared-service-headless","reconcileID":"73f59d0e-ea69-4aa2-b725-91bf8a7df130","error":"failed to get virt service: resource name may not be empty"}
```

This is because those services are owned by the Cluster, but they don't exists in the Virtual Clusters. They are services needed from the Cluster itself (like the kubelet one).

### PR DESCRIPTION
**Pull request by enrichman**
Fix #496 by checking that the Services owned by the Cluster are resources within the virtual cluster.

### CODE REVIEW

File: pkg/controller/cluster/service.go [hunk 1]
```diff
@@ -60,10 +70,11 @@ func (r *ServiceReconciler) Reconcile(ctx context.Context, req reconcile.Request
 	}
 
 	virtualServiceKey := types.NamespacedName{
-		Name:      hostService.Annotations[translate.ResourceNameAnnotation],
-		Namespace: hostService.Annotations[translate.ResourceNamespaceAnnotation],
+		Name:      virtualServiceName,
+		Namespace: virtualServiceNamespace,
 	}
 
+	var virtService v1.Service
```
Comment (galal-hussein) [inline pkg/controller/cluster/service.go]: NIT
```suggestion
	var virtualService v1.Service
```
