### PR TITLE
Schedule Pods in the same Node with a preferred affinity

### LINKED ISSUE #727: Cannot schedule Deployment with PVCs
With PR https://github.com/rancher/k3k/pull/610 we made the change on _where_ the Pod are being scheduled, to have possibly a 1:1 match with the virtual cluster.

In some cases this is not working:
> If you choose to use WaitForFirstConsumer, do not use nodeName in the Pod spec to specify node affinity. If nodeName is used in this case, the scheduler will be bypassed and PVC will remain in pending state.

Also another ref: https://github.com/openebs/openebs/issues/2915

To replicate the issue (using the local-path provisioner):

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: sample-pvc
```

### PR DESCRIPTION
**Pull request by enrichman**
This PR fixes #727 adding a `PreferredDuringSchedulingIgnoredDuringExecution` Affinity to the Pod, instead of an hardcoded `nodeName`.

Also adding some tests, with Deployment and StatefulSet, to avoid regressions.

### CODE REVIEW

File: tests/e2e/cluster_pod_test.go [hunk 1]
```diff
@@ -20,16 +20,132 @@ import (
...
+						},
+					},
+				},
+			}
+
+			pod, err = virtualCluster.Client.CoreV1().Pods(pod.Namespace).Create(ctx, pod, metav1.CreateOptions{})
+			Expect(err).To(Not(HaveOccurred()))
+		})
+
+		It("should have a default Affinity", func() {
```
Comment (JonCrowther) [inline tests/e2e/cluster_pod_test.go]: I think you meant 
```suggestion
		It("should not have the default Affinity", func() {
```
